name: 🚀 SEVER AI STV PREMIUM

on:
  workflow_dispatch:
    inputs:
      duration:
        description: '🕐 Thời gian sử dụng'
        required: false
        default: '5h40m'
        type: choice
        options:
        - '1h'
        - '3h'
        - '5h40m'
        - '6h'
        - '12h'

jobs:
  Premium-RDP-Setup:
    runs-on: windows-2022
    timeout-minutes: 720
    
    steps:
      # BANNER CHÀO MỪNG
      - name: 🎯 KHỞI ĐỘNG HỆ THỐNG
        run: |
          Write-Host ""
          Write-Host ""
          Write-Host "🤖 AI STV PREMIUM RDP SERVER" -ForegroundColor Yellow
          Write-Host "⚡ Powered by AI STV" -ForegroundColor Green
          Write-Host "🕒 Thời gian: ${{ github.event.inputs.duration }}" -ForegroundColor Magenta
          Write-Host ""
          
          # Hiệu ứng loading
          $frames = @('⣾', '⣽', '⣻', '⢿', '⡿', '⣟', '⣯', '⣷')
          for($i=0; $i -lt 10; $i++) {
              Write-Host "`r🚀 Đang khởi tạo hệ thống... $($frames[$i % 8])" -NoNewline -ForegroundColor Blue
              Start-Sleep -Milliseconds 100
          }
          Write-Host "`r✅ Hệ thống đã sẵn sàng!                    " -ForegroundColor Green

      # CẤU HÌNH NÂNG CAO
      - name: 🔧 CẤU HÌNH HỆ THỐNG
        run: |
          Write-Host ""
          Write-Host "🛠️  ĐANG CẤU HÌNH HỆ THỐNG" -ForegroundColor Yellow
          
          $steps = @(
              @{Name="Bật Remote Desktop"; Script={ 
                  Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
              }},
              @{Name="Tắt xác thực mạng"; Script={
                  Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
              }},
              @{Name="Cấu hình bảo mật RDP"; Script={
                  Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "SecurityLayer" -Value 0 -Force
                  Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
              }},
              @{Name="Mở port 3389 firewall"; Script={
                  netsh advfirewall firewall add rule name="RDP-Premium" dir=in action=allow protocol=TCP localport=3389 profile=any
                  netsh advfirewall firewall add rule name="RDP-Premium-Out" dir=out action=allow protocol=TCP localport=3389 profile=any
              }},
              @{Name="Khởi động dịch vụ"; Script={
                  Set-Service -Name TermService -StartupType Automatic -ErrorAction SilentlyContinue
                  Set-Service -Name UmRdpService -StartupType Automatic -ErrorAction SilentlyContinue
                  Start-Service -Name TermService -ErrorAction SilentlyContinue
                  Start-Service -Name UmRdpService -ErrorAction SilentlyContinue
              }}
          )
          
          foreach($step in $steps) {
              Write-Host "│ 📋 $($step.Name)..." -NoNewline -ForegroundColor White
              try {
                  & $step.Script
                  Write-Host "`r│ ✅ $($step.Name)" -ForegroundColor Green
              } catch {
                  Write-Host "`r│ ⚠️  $($step.Name) - Đã bỏ qua lỗi nhỏ" -ForegroundColor Yellow
              }
              Start-Sleep -Milliseconds 500
          }
          
          Write-Host "🎯 Cấu hình hoàn tất!" -ForegroundColor Green

      # TẠO USER PREMIUM - mật khẩu cố định
      - name: 👤 TẠO TÀI KHOẢN PREMIUM
        run: |
          Write-Host ""
          Write-Host "👤 ĐANG TẠO TÀI KHOẢN PREMIUM" -ForegroundColor Yellow

          $matKhau = "AnhKhoa"
          $securePass = ConvertTo-SecureString $matKhau -AsPlainText -Force

          try { Remove-LocalUser -Name "AISTV-PREMIUM" -ErrorAction SilentlyContinue } catch {}
          try { New-LocalUser -Name "AISTV-PREMIUM" -Password $securePass -AccountNeverExpires -Description "AI STV Premium Account" } catch {}
          try { Set-LocalUser -Name "AISTV-PREMIUM" -PasswordNeverExpires $true -ErrorAction SilentlyContinue } catch {}
          try { Add-LocalGroupMember -Group "Administrators" -Member "AISTV-PREMIUM" -ErrorAction SilentlyContinue } catch {}
          try { Add-LocalGroupMember -Group "Remote Desktop Users" -Member "AISTV-PREMIUM" -ErrorAction SilentlyContinue } catch {}
          try { Enable-LocalUser -Name "AISTV-PREMIUM" } catch {}

          echo "$matKhau" > $env:TEMP\rdp_password.txt
          Write-Host "✅ Tài khoản: AISTV-PREMIUM đã sẵn sàng" -ForegroundColor Green

      # TAILSCALE PREMIUM
      - name: 🌐 THIẾT LẬP MẠNG PREMIUM
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        run: |
          Write-Host ""
          Write-Host "🌐 ĐANG THIẾT LẬP KẾT NỐI MẠNG" -ForegroundColor Yellow

          try {
              $msiPath = "$env:TEMP\tailscale-premium.msi"
              Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi" -OutFile $msiPath
              Start-Process msiexec.exe -ArgumentList "/i", "`"$msiPath`"", "/quiet", "/norestart" -Wait
              Remove-Item $msiPath -Force -ErrorAction SilentlyContinue
          } catch {}

          Start-Sleep -Seconds 10

          try {
              & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=$env:TAILSCALE_AUTH_KEY --hostname=ai-stv-premium-$env:GITHUB_RUN_ID --accept-routes --accept-dns --reset
          } catch {}

          $ip = $null
          for($i=0; $i -lt 20; $i++) {
              try {
                  $ip = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4 2>&1
                  if ($ip -and $ip -match '^\d+\.\d+\.\d+\.\d+$') {
                      echo "TAILSCALE_IP=$ip" >> $env:GITHUB_ENV
                      break
                  }
              } catch {}
              Start-Sleep -Seconds 3
          }
          if (-not $ip) { echo "TAILSCALE_IP=localhost" >> $env:GITHUB_ENV }

      # HIỂN THỊ THÔNG TIN
      - name: 🎉 THÔNG TIN KẾT NỐI
        run: |
          $matKhau = Get-Content $env:TEMP\rdp_password.txt -ErrorAction SilentlyContinue
          if (-not $matKhau) { $matKhau = "Không thể đọc mật khẩu" }
          Write-Host "🌐 IP: $env:TAILSCALE_IP" -ForegroundColor Cyan
          Write-Host "👤 User: AISTV-PREMIUM" -ForegroundColor White
          Write-Host "🔑 Pass: $matKhau" -ForegroundColor White
          Write-Host "📍 Port: 3389" -ForegroundColor White

      # DUY TRÌ PHIÊN LÀM VIỆC
      - name: ⏳ DUY TRÌ PHIÊN LÀM VIỆC
        run: |
          $totalMinutes = switch ("${{ github.event.inputs.duration }}") {
              "1h" { 60 }
              "3h" { 180 }
              "5h40m" { 340 }
              "6h" { 360 }
              "12h" { 720 }
          }
          $timeZone = [System.TimeZoneInfo]::FindSystemTimeZoneById("SE Asia Standard Time")
          $thoiGianBatDau = [System.TimeZoneInfo]::ConvertTimeFromUtc((Get-Date).ToUniversalTime(), $timeZone)
          $thoiGianKetThuc = $thoiGianBatDau.AddMinutes($totalMinutes)
          $monitorScript = { while ($true) { $termService = Get-Service -Name TermService -ErrorAction SilentlyContinue; if ($termService.Status -ne 'Running') { Start-Service -Name TermService -ErrorAction SilentlyContinue }; Start-Sleep -Seconds 30 } }
          Start-Job -ScriptBlock $monitorScript -Name "SystemMonitor"

      # DỌN DẸP HỆ THỐNG
      - name: 🧹 DỌN DẸP HỆ THỐNG
        if: always()
        run: |
          $cleanupSteps = @(
              @{Name="Xóa file password"; Script={ Remove-Item "$env:TEMP\rdp_password.txt" -ErrorAction SilentlyContinue }},
              @{Name="Vô hiệu hóa user"; Script={ Disable-LocalUser -Name "AISTV-PREMIUM" -ErrorAction SilentlyContinue }},
              @{Name="Đóng kết nối mạng"; Script={ & "$env:ProgramFiles\Tailscale\tailscale.exe" down --accept-risk=all -ErrorAction SilentlyContinue; Start-Sleep -Seconds 5 }},
              @{Name="Xóa rule firewall"; Script={ netsh advfirewall firewall delete rule name="RDP-Premium" dir=in -ErrorAction SilentlyContinue; netsh advfirewall firewall delete rule name="RDP-Premium-Out" dir=out -ErrorAction SilentlyContinue }},
              @{Name="Khôi phục cài đặt RDP"; Script={ Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 1 -Force; Stop-Service -Name TermService -Force -ErrorAction SilentlyContinue }}
          )
          foreach($step in $cleanupSteps) { try { & $step.Script } catch {} }
